framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                    - App\CommandBus\Middleware\DummyBusMiddleware
