parameters:
    container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\:
        resource: '../src/'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    _instanceof:
        App\CommandBus\Common\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }
